import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import { ProgressBarProvider } from "@/providers/progress-bar-provider";

export const metadata: Metadata = {
  title: {
    template: "%s | Tugasku",
    default: "Tugasku",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="min-w-[250px]"
    >
      <body suppressHydrationWarning>
        <Toaster position="bottom-right" />
        <ProgressBarProvider>{children}</ProgressBarProvider>
      </body>
    </html>
  );
}
