import type { Metadata } from "next";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: {
    template: "%s | Tugasku",
    default: "Tugasku",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="min-w-[250px]"
    >
      <body suppressHydrationWarning>
        <NextTopLoader
          color="#6034D4"
          showSpinner={false}
        />
        <Toaster position="bottom-right" />
        {children}
      </body>
    </html>
  );
}
